import type { Metadata } from "next";
import { Geist, Geist_Mono, Miriam_Libre,  } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/components/header/Navbar";
import Footer from "./shared/components/footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const MyriadPro = Miriam_Libre({
  variable: "--font-myriad-pro",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${MyriadPro.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
